const SET_USER_DETAIL = 'SET_USER_DETAIL';
const GET_USER_TOKEN_SAGA = 'GET_USER_TOKEN_SAGA';
const SET_ERROR_STATE = 'SET_ERROR_STATE'

export {
    SET_USER_DETAIL,
    GET_USER_TOKEN_SAGA,
    SET_ERROR_STATE,
}